name: build  # Name of the conda environment
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - breathe
  - cffi
  - colorama
  - cython
  - docopt
  - numpy
  - pyyaml
  - sphinx